language: r
dist: bionic
cache: packages

r_github_packages:
  - richelbilderbeek/beautier
  - richelbilderbeek/beastier
  - richelbilderbeek/babette
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling
  - richelbilderbeek/mcbette
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette

before_install:
  - sudo apt-get update
  # ImageMagick
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  - sudo apt install -qq libmpfr-dev
  # proselint
  - sudo pip install proselint
  # Python3 and pip
  - sudo apt install python3-pip
  - sudo pip install --upgrade pip

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz
  # mhcnuggetsr
  - cd scripts && ./install_mhcnuggetsr.sh && cd ..
  - cd scripts && ./check_mhcnuggetsr.sh && cd ..
  # BEAST2
  - cd scripts ; ./install_beast2.sh ; cd ..
  - cd scripts ; ./check_beast2.sh ; cd ..
  # babette
  - cd scripts ; ./install_babette.sh ; cd ..
  # mcbette
  - cd scripts ; ./install_mcbette.sh ; cd ..
  - cd scripts ; ./check_mcbette.sh ; cd ..
  # pirouette
  - cd scripts ; ./install_pirouette.sh ; cd ..
  # razzo
  - cd scripts ; ./install_razzo.sh ; cd ..
  # EpitopePrediction
  - cd scripts ; ./install_epitope_prediction.sh ; cd ..
  # pureseqtmr
  - cd scripts ; ./install_pureseqtmr.sh ; cd ..
  # BBBQ
  - cd scripts ; ./install_bbbq.sh ; cd ..
  # Peregrine?
  - cd scripts ; ./install_peregrine.sh ; cd ..

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links

after_failure:
  - cat /home/travis/build/richelbilderbeek/peregrine/peregrine.Rcheck/00check.log
  - cat /home/travis/build/richelbilderbeek/peregrine/peregrine.Rcheck/00install.out

